apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/leolee-rac/argocd-poc.git
    targetRevision: HEAD
    path: charts/root-app
  destination:
    server: in-cluster
    namespaces: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
