apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/leolee-rac/argocd-poc.git
    path: charts/argo-cd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true