apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: default
spec:
   project: default
   source:
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: guestbook
   destination:
      server: {{ .Values.spec.destination.server }}
      namespaces: {{ .Values.spec.destination.namespace }}
   syncPolicy:
         syncOptions:
         - CreateNamespace=true
         automated:
         prune: true
         selfHeal: true