# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 5.46.8
    repository: https://argoproj.github.io/argo-helm
