# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
apiVersion: v2
name: argo-cd
version: 1.1.1
dependencies:
  - name: argo-cd
    version: 7.0.0
    repository: https://argoproj.github.io/argo-helm
