redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  service:
    type: LoadBalancer
  autoscaling:
    enabled: true
    minReplicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicas: 1

